/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 对话选项中的消息（JS 返回值形态） */
export interface ChatChoiceJs {
  /** 选项索引 */
  index: number
  /** 生成的回复消息 */
  message: ChoiceMessageJs
  /** 结束原因（stop / length / content_filter / tool_calls） */
  finishReason?: string
}
/** 完成结果中的消息 */
export interface ChoiceMessageJs {
  /** 角色（通常为 "assistant"） */
  role: string
  /** 消息内容 */
  content?: string
}
/** Token 使用统计 */
export interface ChatUsageJs {
  /** 提示词 token 数 */
  promptTokens: number
  /** 完成回复 token 数 */
  completionTokens: number
  /** 总 token 数 */
  totalTokens: number
}
/** 对话完成结果 */
export interface ChatCompletionJs {
  /** 响应 ID */
  id: string
  /** 对象类型 */
  object: string
  /** 创建时间戳（秒） */
  created: number
  /** 使用的模型 */
  model: string
  /** 回复选项列表 */
  choices: Array<ChatChoiceJs>
  /** Token 使用统计 */
  usage?: ChatUsageJs
  /** 服务层级 */
  serviceTier?: string
  /** 系统指纹 */
  systemFingerprint?: string
}
/** 流式增量消息 */
export interface DeltaMessageJs {
  /** 角色（首个块通常为 "assistant"） */
  role?: string
  /** 增量内容 */
  content?: string
}
/** 流式增量 */
export interface ChatCompletionDeltaJs {
  /** 增量索引 */
  index: number
  /** 增量消息内容 */
  delta: DeltaMessageJs
  /** 结束原因 */
  finishReason?: string
}
/** 流式对话块 */
export interface ChatCompletionChunkJs {
  /** 响应 ID */
  id: string
  /** 对象类型 */
  object: string
  /** 创建时间戳（秒） */
  created: number
  /** 使用的模型 */
  model: string
  /** 增量选项列表 */
  choices: Array<ChatCompletionDeltaJs>
  /** Token 使用统计（仅末尾块可能出现） */
  usage?: ChatUsageJs
}
/** 文字转语音结果 */
export interface SpeechResultJs {
  /** 音频二进制数据（JS Buffer） */
  audioData: Buffer
  /** 音频 MIME 类型 */
  contentType: string
  /** 音频格式（mp3/wav/opus 等） */
  format: string
  /** 估计音频时长（秒） */
  duration?: number
  /** 使用的模型 ID */
  model?: string
  /** 音频 URL（部分 Provider 返回） */
  audioUrl?: string
}
/** 图像数据（JS 返回值形态） */
export interface ImageDataJs {
  /** 图像 URL */
  url?: string
  /** Base64 编码的图像 */
  b64Json?: string
  /** 修改后的提示词（如模型优化过） */
  revisedPrompt?: string
}
/** 图像生成结果（JS 返回值形态） */
export interface ImageResultJs {
  /** 响应 ID */
  id: string
  /** 对象类型 */
  object: string
  /** 创建时间戳 */
  created: number
  /** 使用的模型 */
  model: string
  /** 生成的图像列表 */
  data: Array<ImageDataJs>
}
/** 视频任务信息（JS 返回值形态） */
export interface VideoTaskJs {
  /** 任务 ID（用于轮询状态） */
  taskId: string
  /** 使用的模型 */
  model: string
  /** 任务状态（pending / processing / success / failed） */
  status: string
  /** 创建时间戳 */
  createdAt: number
}
/** 视频任务状态（JS 返回值形态） */
export interface VideoStatusJs {
  /** 任务 ID */
  taskId: string
  /** 任务状态 */
  status: string
  /** 视频 URL（成功时） */
  videoUrl?: string
  /** 进度 0-100 */
  progress?: number
  /** 错误信息（失败时） */
  error?: string
  /** 创建时间戳 */
  createdAt?: number
  /** 更新时间戳 */
  updatedAt?: number
}
/** 嵌入项（JS 返回值形态） */
export interface EmbeddingItemJs {
  /** 对象类型（固定 "embedding"） */
  object: string
  /** 索引 */
  index: number
  /** 嵌入向量（浮点列表） */
  embedding: Array<number>
}
/** 嵌入使用统计 */
export interface EmbeddingUsageJs {
  /** 提示词 token 数 */
  promptTokens: number
  /** 总 token 数 */
  totalTokens: number
}
/** 嵌入结果（JS 返回值形态） */
export interface EmbeddingResultJs {
  /** 对象类型（固定 "list"） */
  object: string
  /** 嵌入向量列表 */
  data: Array<EmbeddingItemJs>
  /** 使用的模型 */
  model: string
  /** 使用统计 */
  usage?: EmbeddingUsageJs
}
/** 转写分段信息（JS 返回值形态） */
export interface TranscriptionSegmentJs {
  /** 分段 ID */
  id: number
  /** 开始时间（秒） */
  start: number
  /** 结束时间（秒） */
  end: number
  /** 分段文本 */
  text: string
  /** 分段置信度（0-1） */
  confidence?: number
  /** 说话人标识（说话人分离时使用） */
  speaker?: string
}
/** 转写词级时间戳信息（JS 返回值形态） */
export interface TranscriptionWordJs {
  /** 词文本 */
  word: string
  /** 开始时间（秒） */
  start: number
  /** 结束时间（秒） */
  end: number
  /** 置信度（0-1） */
  confidence?: number
}
/** 转写结果（JS 返回值形态） */
export interface TranscriptionResultJs {
  /** 完整转写文本 */
  text: string
  /** 检测到的语言 */
  language?: string
  /** 音频时长（秒） */
  duration?: number
  /** 分段信息 */
  segments?: Array<TranscriptionSegmentJs>
  /** 词级时间戳 */
  words?: Array<TranscriptionWordJs>
  /** 任务类型（transcribe / translate） */
  task: string
  /** 使用统计 */
  usage?: any
  /** 使用的模型 ID */
  model?: string
}
/** 模型信息（JS 返回值形态） */
export interface ModelInfoJs {
  /** 模型标识符 */
  id: string
  /** 模型显示名称 */
  name: string
  /** 模型类型（chat / image / video / audio） */
  modelType: string
  /** 提供商名称 */
  provider: string
  /** 支持的能力列表 */
  capabilities: Array<string>
  /** 最大 token 数（仅 chat 模型） */
  maxTokens?: number
  /** 是否支持流式输出 */
  supportsStreaming: boolean
  /** 模型描述 */
  description?: string
  /** 模型创建时间戳 */
  created?: number
}
/** 语音信息（JS 返回值形态） */
export interface VoiceInfoJs {
  /** 音色短名 */
  shortName?: string
  /** 音色显示名 */
  name?: string
  /** 语言区域 */
  locale?: string
  /** 性别 */
  gender?: string
  /** 音色 ID */
  voiceId?: string
}
/**
 * AIBridge 统一客户端
 *
 * 直连 aibridge-core 的 `Client`。所有异步方法返回 JS `Promise`。
 *
 * 示例（JS）：
 * ```js
 * const { Client } = require('aibridge');
 * const client = new Client('echo', {});
 * await client.start();
 * const resp = await client.chat({ model: 'echo-chat', messages: [{ role: 'user', content: 'hello' }] });
 * await client.close();
 * ```
 */
export declare class Client {
  /**
   * 创建客户端
   *
   * `provider` 为 Provider 类型（如 "echo"、"openai"、"agnes"）。
   * `options` 为连接选项（api_key / base_url / timeout 等，可选字段）。
   */
  constructor(provider: string, options?: any | undefined | null)
  /** 启动客户端（初始化适配器） */
  start(): Promise<void>
  /** 关闭客户端（释放资源） */
  close(): Promise<void>
  /**
   * 文本对话
   *
   * `request` 形如 `{ model, messages: [{ role, content }], temperature?, max_tokens? }`。
   * 透传不识别的字段到 core 的 `extra`（厂商特有参数）。
   */
  chat(request: any): Promise<ChatCompletionJs>
  /**
   * 流式文本对话
   *
   * 返回 `ChatStreamIterator`，支持 JS `for await...of` 迭代 `ChatCompletionChunk`。
   */
  chatStream(request: any): Promise<ChatStreamIterator>
  /**
   * 文字转语音
   *
   * `request` 形如 `{ model, input, voice, response_format?, speed? }`。
   * `voice` 可为字符串（单个音色）或字符串数组（候选列表，用于自动降级）。
   * 返回 `SpeechResultJs`，`audio_data` 为 JS `Buffer`。
   */
  speech(request: any): Promise<SpeechResultJs>
  /**
   * 图像生成
   *
   * `request` 形如 `{ model, prompt, size?, n?, quality?, style? }`。
   * 返回 `ImageResultJs`，包含生成的图像列表。
   */
  imageGenerate(request: any): Promise<ImageResultJs>
  /**
   * 视频生成（创建异步任务）
   *
   * `request` 形如 `{ model, prompt, width?, height?, duration?, aspect_ratio?, mode? }`。
   * 返回 `VideoTaskJs`，包含 `task_id` 用于后续轮询。
   */
  videoCreate(request: any): Promise<VideoTaskJs>
  /**
   * 视频生成状态轮询
   *
   * `task_id` 为 `video_create` 返回的任务 ID，`model` 为使用的模型。
   * 返回 `VideoStatusJs`，包含进度、结果 URL 或错误信息。
   */
  videoPoll(taskId: string, model: string): Promise<VideoStatusJs>
  /**
   * 文本嵌入
   *
   * `request` 形如 `{ model, input: "text" | ["text1", "text2"] }`。
   * 返回 `EmbeddingResultJs`，包含向量列表。
   */
  embed(request: any): Promise<EmbeddingResultJs>
  /**
   * 语音转文字（ASR 转写）
   *
   * `request` 形如 `{ model, file, language?, response_format? }`。
   * `file` 为音频路径、URL、Base64 或二进制数据。
   * 返回 `TranscriptionResultJs`，包含文本、分段和时间戳。
   */
  transcribe(request: any): Promise<TranscriptionResultJs>
  /**
   * 语音翻译（将非英文音频翻译为英文）
   *
   * 参数与 `transcribe` 相同，内部设置 `translate=true`。
   * 返回 `TranscriptionResultJs`，文本为英文。
   */
  translate(request: any): Promise<TranscriptionResultJs>
  /**
   * 列出可用模型
   *
   * `filter` 可选，为 "chat" / "image" / "video" / "audio" 之一，
   * 用于按模型类型过滤；省略则返回全部。
   * 返回 `ModelInfo` 列表。
   */
  listModels(filter?: string | undefined | null): Promise<Array<ModelInfoJs>>
  /**
   * 列出可用音色
   *
   * `language` 可选，为语言区域代码（如 "zh-CN"），用于过滤音色。
   * 返回 `VoiceInfo` 列表。
   */
  listVoices(language?: string | undefined | null): Promise<Array<VoiceInfoJs>>
  /**
   * 推荐可用音色
   *
   * `language` 为语言区域代码（如 "zh-CN"），`gender` 为 "Male" / "Female"，
   * `limit` 为推荐数量上限。
   * 返回 `VoiceInfo` 列表。
   */
  recommendVoices(language: string | undefined | null, gender: string | undefined | null, limit: number): Promise<Array<VoiceInfoJs>>
}
/**
 * 流式对话迭代器
 *
 * 由 `Client.chatStream()` 返回。通过 `[Symbol.asyncIterator]`（index.js 中安装）
 * 支持 JS `for await...of` 语法迭代 `ChatCompletionChunk`。
 *
 * 也可直接调用 `.next()` 方法手动迭代（返回 `null` 表示结束）。
 */
export declare class ChatStreamIterator {
  /**
   * 拉取下一个 chunk
   *
   * 返回 `ChatCompletionChunk`，流结束时返回 `null`。
   * 流内部错误以 `napi::Error`（reject）形式抛出。
   */
  next(): Promise<ChatCompletionChunkJs | null>
}
