/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 对话选项中的消息（JS 返回值形态） */
export interface ChatChoiceJs {
  /** 选项索引 */
  index: number
  /** 生成的回复消息 */
  message: ChoiceMessageJs
  /** 结束原因（stop / length / content_filter / tool_calls） */
  finishReason?: string
}
/** 完成结果中的消息 */
export interface ChoiceMessageJs {
  /** 角色（通常为 "assistant"） */
  role: string
  /** 消息内容 */
  content?: string
}
/** Token 使用统计 */
export interface ChatUsageJs {
  /** 提示词 token 数 */
  promptTokens: number
  /** 完成回复 token 数 */
  completionTokens: number
  /** 总 token 数 */
  totalTokens: number
}
/** 对话完成结果 */
export interface ChatCompletionJs {
  /** 响应 ID */
  id: string
  /** 对象类型 */
  object: string
  /** 创建时间戳（秒） */
  created: number
  /** 使用的模型 */
  model: string
  /** 回复选项列表 */
  choices: Array<ChatChoiceJs>
  /** Token 使用统计 */
  usage?: ChatUsageJs
  /** 服务层级 */
  serviceTier?: string
  /** 系统指纹 */
  systemFingerprint?: string
}
/** 流式增量消息 */
export interface DeltaMessageJs {
  /** 角色（首个块通常为 "assistant"） */
  role?: string
  /** 增量内容 */
  content?: string
}
/** 流式增量 */
export interface ChatCompletionDeltaJs {
  /** 增量索引 */
  index: number
  /** 增量消息内容 */
  delta: DeltaMessageJs
  /** 结束原因 */
  finishReason?: string
}
/** 流式对话块 */
export interface ChatCompletionChunkJs {
  /** 响应 ID */
  id: string
  /** 对象类型 */
  object: string
  /** 创建时间戳（秒） */
  created: number
  /** 使用的模型 */
  model: string
  /** 增量选项列表 */
  choices: Array<ChatCompletionDeltaJs>
  /** Token 使用统计（仅末尾块可能出现） */
  usage?: ChatUsageJs
}
/** 文字转语音结果 */
export interface SpeechResultJs {
  /** 音频二进制数据（JS Buffer） */
  audioData: Buffer
  /** 音频 MIME 类型 */
  contentType: string
  /** 音频格式（mp3/wav/opus 等） */
  format: string
  /** 估计音频时长（秒） */
  duration?: number
  /** 使用的模型 ID */
  model?: string
  /** 音频 URL（部分 Provider 返回） */
  audioUrl?: string
}
/**
 * AIBridge 统一客户端
 *
 * 直连 aibridge-core 的 `Client`。所有异步方法返回 JS `Promise`。
 *
 * 示例（JS）：
 * ```js
 * const { Client } = require('aibridge');
 * const client = new Client('echo', {});
 * await client.start();
 * const resp = await client.chat({ model: 'echo-chat', messages: [{ role: 'user', content: 'hello' }] });
 * await client.close();
 * ```
 */
export declare class Client {
  /**
   * 创建客户端
   *
   * `provider` 为 Provider 类型（如 "echo"、"openai"、"agnes"）。
   * `options` 为连接选项（api_key / base_url / timeout 等，可选字段）。
   */
  constructor(provider: string, options?: any | undefined | null)
  /** 启动客户端（初始化适配器） */
  start(): Promise<void>
  /** 关闭客户端（释放资源） */
  close(): Promise<void>
  /**
   * 文本对话
   *
   * `request` 形如 `{ model, messages: [{ role, content }], temperature?, max_tokens? }`。
   * 透传不识别的字段到 core 的 `extra`（厂商特有参数）。
   */
  chat(request: any): Promise<ChatCompletionJs>
  /**
   * 流式文本对话
   *
   * 返回 `ChatStreamIterator`，支持 JS `for await...of` 迭代 `ChatCompletionChunk`。
   */
  chatStream(request: any): Promise<ChatStreamIterator>
  /**
   * 文字转语音
   *
   * `request` 形如 `{ model, input, voice, response_format?, speed? }`。
   * `voice` 可为字符串（单个音色）或字符串数组（候选列表，用于自动降级）。
   * 返回 `SpeechResultJs`，`audio_data` 为 JS `Buffer`。
   */
  speech(request: any): Promise<SpeechResultJs>
}
/**
 * 流式对话迭代器
 *
 * 由 `Client.chatStream()` 返回。通过 `[Symbol.asyncIterator]`（index.js 中安装）
 * 支持 JS `for await...of` 语法迭代 `ChatCompletionChunk`。
 *
 * 也可直接调用 `.next()` 方法手动迭代（返回 `null` 表示结束）。
 */
export declare class ChatStreamIterator {
  /**
   * 拉取下一个 chunk
   *
   * 返回 `ChatCompletionChunk`，流结束时返回 `null`。
   * 流内部错误以 `napi::Error`（reject）形式抛出。
   */
  next(): Promise<ChatCompletionChunkJs | null>
}
